const TelegramBot = require('node-telegram-bot-api');
const db = require('../db');
const authService = require('./authService');

const token = process.env.TELEGRAM_TOKEN;
let bot;

// ─── Helper: format a rich signal message ────────────────────────────────────
function formatEntryMessage(strategyName, signal) {
  const { symbol, side, price, tp, sl, stakeAmount } = signal;
  const isLong = side === 'buy' || side === 'long';
  const sideEmoji = isLong ? '🟢' : '🔴';
  const sideLabel = isLong ? '📈 BUY (LONG)' : '📉 SELL (SHORT)';

  return (
    `${sideEmoji} *NEW SIGNAL — ${strategyName}*\n` +
    `━━━━━━━━━━━━━━━━━━━━━━\n` +
    `*Pair:*         \`${symbol}\`\n` +
    `*Direction:*    ${sideLabel}\n` +
    `*Entry Price:*  \`$${Number(price).toFixed(4)}\`\n` +
    `*Take Profit:*  \`$${Number(tp).toFixed(4)}\` 🎯\n` +
    `*Stop Loss:*    \`$${Number(sl).toFixed(4)}\` 🛑\n` +
    `*Stake:*        \`$${stakeAmount || 100}\`\n` +
    `━━━━━━━━━━━━━━━━━━━━━━\n` +
    `_Signal generated by BritSyncAI_`
  );
}

function formatExitMessage(strategyName, signal) {
  const { symbol, side, price, pnl } = signal;
  const isProfit = (pnl || 0) >= 0;
  const pnlEmoji = isProfit ? '🟢' : '🔴';
  const pnlSign = isProfit ? '+' : '';
  const outcomeLabel = signal.status === 'tp_hit' ? '🎯 Take Profit Hit' : (signal.status === 'sl_hit' ? '🛑 Stop Loss Hit' : '✅ Trade Closed');

  return (
    `${pnlEmoji} *${outcomeLabel} — ${strategyName}*\n` +
    `━━━━━━━━━━━━━━━━━━━━━━\n` +
    `*Pair:*         \`${symbol}\`\n` +
    `*Exit Side:*    ${side.toUpperCase()}\n` +
    `*Exit Price:*   \`$${Number(price).toFixed(4)}\`\n` +
    `*PnL:*          ${pnlEmoji} \`${pnlSign}${Number(pnl || 0).toFixed(2)}%\`\n` +
    `━━━━━━━━━━━━━━━━━━━━━━\n` +
    `_BritSyncAI Trading Terminal_`
  );
}

// ─── Bot Setup ────────────────────────────────────────────────────────────────
if (token && token !== 'your_telegram_bot_token_here') {
  bot = new TelegramBot(token, { polling: { interval: 1000, autoStart: false, params: { timeout: 10 } } });
  bot.startPolling({ restart: false, dropPendingUpdates: true });
  console.log('[Telegram] Bot initialized: @BritSyncAI_bot');

  const sessions = {}; // tracks per-chat registration state

  // /start — greet & prompt login
  bot.onText(/\/start/, (msg) => {
    const chatId = msg.chat.id;
    sessions[chatId] = { step: 'email' };
    bot.sendMessage(chatId,
      `🤖 *Welcome to BritSyncAI Signal Bot!*\n\n` +
      `You will receive live trading signals for your purchased strategies.\n\n` +
      `Please enter your *account email* to link your account:`,
      { parse_mode: 'Markdown' }
    );
  });

  // /help — list commands
  bot.onText(/\/help/, (msg) => {
    bot.sendMessage(msg.chat.id,
      `📋 *Available Commands*\n\n` +
      `/start — Link your BritSyncAI account\n` +
      `/mystrats — Show your subscribed strategies\n` +
      `/logout — Unlink Telegram from your account\n` +
      `/help — Show this menu`,
      { parse_mode: 'Markdown' }
    );
  });

  // /mystrats — show which strategies user is subscribed to
  bot.onText(/\/mystrats/, async (msg) => {
    const chatId = msg.chat.id;
    const user = await db.get("SELECT id, email FROM users WHERE telegramId = ?", [chatId.toString()]);
    if (!user) {
      return bot.sendMessage(chatId, '❌ You are not linked. Send /start to connect your account.');
    }

    const subs = await db.query(
      "SELECT s.name, s.type FROM strategies s JOIN subscriptions sub ON s.id = sub.strategyId WHERE sub.userId = ?",
      [user.id]
    );

    if (subs.length === 0) {
      return bot.sendMessage(chatId,
        `📭 *No active strategies found.*\n\nPurchase a plan on the dashboard to receive signals.`,
        { parse_mode: 'Markdown' }
      );
    }

    const stratList = subs.map(s => `• *${s.name}* (${s.type})`).join('\n');
    bot.sendMessage(chatId,
      `📊 *Your Active Signal Subscriptions:*\n\n${stratList}\n\n` +
      `_You will receive BUY/SELL signals for all of the above strategies._`,
      { parse_mode: 'Markdown' }
    );
  });

  // /logout — unlink account
  bot.onText(/\/logout/, async (msg) => {
    await db.run("UPDATE users SET telegramId = NULL WHERE telegramId = ?", [msg.chat.id.toString()]);
    bot.sendMessage(msg.chat.id, '👋 You have been unlinked from BritSyncAI signal alerts.');
  });

  // message handler — email/password login flow
  bot.on('message', async (msg) => {
    const chatId = msg.chat.id;
    const text = msg.text;
    const session = sessions[chatId];

    if (!session || !text || text.startsWith('/')) return;

    if (session.step === 'email') {
      session.email = text.trim();
      session.step = 'password';
      bot.sendMessage(chatId, '🔑 Got it! Now enter your *password*:', { parse_mode: 'Markdown' });
    } else if (session.step === 'password') {
      try {
        const { user } = await authService.login(session.email, text);
        await db.run("UPDATE users SET telegramId = ? WHERE id = ?", [chatId.toString(), user.id]);

        // Fetch their subscriptions to confirm
        const subs = await db.query(
          "SELECT s.name FROM strategies s JOIN subscriptions sub ON s.id = sub.strategyId WHERE sub.userId = ?",
          [user.id]
        );

        const stratList = subs.length > 0
          ? subs.map(s => `• *${s.name}*`).join('\n')
          : '_No active strategies yet — purchase a plan on the dashboard._';

        bot.sendMessage(chatId,
          `✅ *Linked successfully!*\n\n` +
          `Account: \`${user.email}\`\n\n` +
          `📊 *Your subscribed strategies:*\n${stratList}\n\n` +
          `You will now receive real-time BUY/SELL signals with entry price, take profit, and stop loss.\n\n` +
          `Send /help to see all commands.`,
          { parse_mode: 'Markdown' }
        );
        delete sessions[chatId];
      } catch (e) {
        bot.sendMessage(chatId, `❌ Login failed: ${e.message}\n\nSend /start to try again.`);
        delete sessions[chatId];
      }
    }
  });

} else {
  console.log('[Telegram] TELEGRAM_TOKEN missing or not configured. Bot disabled.');
}

// ─── TelegramService class ────────────────────────────────────────────────────
class TelegramService {

  async connect(userId, telegramId) {
    if (!telegramId) throw new Error('telegramId is required');
    return await db.run("UPDATE users SET telegramId = ? WHERE id = ?", [telegramId.toString(), userId]);
  }

  async disconnect(userId) {
    return await db.run("UPDATE users SET telegramId = NULL WHERE id = ?", [userId]);
  }

  async sendDirectNotification(telegramId, message) {
    if (!bot || !telegramId) return;
    bot.sendMessage(telegramId, message, { parse_mode: 'Markdown' }).catch(console.error);
  }

  /**
   * Broadcast an ENTRY signal (buy/sell/long/short) to all users subscribed to this strategy.
   * Filters strictly: only users who have a subscription row for this strategyId receive it.
   */
  async broadcastSignal(signal) {
    if (!bot) return;

    const { strategyId, side } = signal;

    const strategy = await db.get("SELECT name FROM strategies WHERE id = ?", [strategyId]);
    if (!strategy) return;

    // Only subscribed users with a linked telegramId
    const users = await db.query(
      `SELECT DISTINCT u.telegramId
       FROM users u
       JOIN subscriptions s ON u.id = s.userId
       WHERE s.strategyId = ? AND u.telegramId IS NOT NULL`,
      [strategyId]
    );

    if (users.length === 0) return;

    const isEntry = ['buy', 'long', 'sell', 'short'].includes((side || '').toLowerCase());
    const message = isEntry
      ? formatEntryMessage(strategy.name, signal)
      : formatExitMessage(strategy.name, signal);

    console.log(`[Telegram] Broadcasting signal to ${users.length} user(s) for strategy ${strategy.name} (${side})`);

    for (const user of users) {
      bot.sendMessage(user.telegramId, message, { parse_mode: 'Markdown' }).catch(console.error);
    }
  }

  /**
   * Broadcast a CLOSE/EXIT signal when a trade is closed (TP hit / SL hit / manual close).
   * Called from strategyService signal tracker or paperService.
   */
  async broadcastClose(strategyId, symbol, side, price, pnl, status) {
    if (!bot) return;

    const strategy = await db.get("SELECT name FROM strategies WHERE id = ?", [strategyId]);
    if (!strategy) return;

    const users = await db.query(
      `SELECT DISTINCT u.telegramId
       FROM users u
       JOIN subscriptions s ON u.id = s.userId
       WHERE s.strategyId = ? AND u.telegramId IS NOT NULL`,
      [strategyId]
    );

    if (users.length === 0) return;

    const signal = { symbol, side, price, pnl, status };
    const message = formatExitMessage(strategy.name, signal);

    console.log(`[Telegram] Broadcasting close to ${users.length} user(s): ${symbol} ${status} PnL=${pnl?.toFixed(2)}%`);

    for (const user of users) {
      bot.sendMessage(user.telegramId, message, { parse_mode: 'Markdown' }).catch(console.error);
    }
  }

  // Legacy compat — kept for paperService calls
  async notifyTradeClosed(telegramId, strategyName, symbol, side, price, pnl) {
    if (!bot || !telegramId) return;
    const signal = { symbol, side, price, pnl, status: 'closed' };
    const message = formatExitMessage(strategyName, signal);
    bot.sendMessage(telegramId, message, { parse_mode: 'Markdown' }).catch(console.error);
  }
}

module.exports = new TelegramService();
