import { Navbar } from '../components/layout/Navbar';
import { Footer } from '../components/layout/Footer';
import { Activity, Shield, Cpu } from 'lucide-react';

export default function About() {
  return (
    <div className="min-h-screen bg-[#020617] text-slate-300 font-sans">
      <Navbar />
      <main className="pt-32 pb-24 container mx-auto px-6">

        {/* Hero Section */}
        <div className="max-w-4xl mx-auto text-center mb-24">
          <h1 className="text-5xl md:text-6xl font-bold text-white mb-6 tracking-tighter">
            Leveling the Playing Field for <span className="text-cyan-400">Retail Traders</span>
          </h1>
          <p className="text-xl text-slate-400 leading-relaxed">
            BritTrade was founded on a simple principle: institutional-grade algorithmic trading tools should be accessible to everyone, not just Wall Street hedge funds.
          </p>
        </div>

        {/* Mission / Vision */}
        <div className="grid md:grid-cols-2 gap-16 items-center mb-24 max-w-6xl mx-auto">
          <div>
            <h2 className="text-3xl font-bold text-white mb-6">Our Mission</h2>
            <p className="text-slate-400 mb-4 leading-relaxed">
              We are a team of quantitative analysts, full-stack engineers, and crypto enthusiasts dedicated to removing emotion from trading.
            </p>
            <p className="text-slate-400 leading-relaxed">
              By leveraging advanced cloud infrastructure and machine learning algorithms, we process vast amounts of market data in real-time, executing high-probability setups while you sleep.
            </p>
          </div>
          <div className="relative">
            <div className="absolute -inset-4 bg-gradient-to-r from-cyan-500/20 to-purple-500/20 blur-2xl rounded-full"></div>
            <div className="bg-slate-900 border border-white/10 rounded-3xl p-8 relative z-10 aspect-square flex flex-col items-center justify-center text-center">
              <Activity className="w-20 h-20 text-cyan-400 mb-6" />
              <h3 className="text-2xl font-bold text-white mb-2">2.4M+</h3>
              <p className="text-slate-500">Market Events Processed Daily</p>
            </div>
          </div>
        </div>

        {/* Core Values */}
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl font-bold text-white mb-12 text-center">Platform Pillars</h2>
          <div className="grid md:grid-cols-3 gap-8">
            <div className="bg-slate-900/50 border border-white/5 p-8 rounded-3xl">
              <Cpu className="w-12 h-12 text-purple-400 mb-6" />
              <h3 className="text-xl font-bold text-white mb-4">Data-Driven Execution</h3>
              <p className="text-slate-400 leading-relaxed">We don't rely on gut feelings. Every signal is generated by rigorous backtesting and real-time quantitative analysis.</p>
            </div>
            <div className="bg-slate-900/50 border border-white/5 p-8 rounded-3xl">
              <Shield className="w-12 h-12 text-cyan-400 mb-6" />
              <h3 className="text-xl font-bold text-white mb-4">Uncompromising Security</h3>
              <p className="text-slate-400 leading-relaxed">Your funds never leave your exchange. We utilize non-custodial API architecture and military-grade encryption.</p>
            </div>
            <div className="bg-slate-900/50 border border-white/5 p-8 rounded-3xl">
              <Activity className="w-12 h-12 text-emerald-400 mb-6" />
              <h3 className="text-xl font-bold text-white mb-4">Complete Transparency</h3>
              <p className="text-slate-400 leading-relaxed">We publish comprehensive performance metrics. If a strategy has a drawdown, you see it instantly.</p>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
